engineStrict: true

gitBranchLockfile: true

mergeGitBranchLockfilesBranchPattern:
  - main
  - release*

allowBuilds:
  esbuild: true
  sharp: true

shellEmulator: true

verifyDepsBeforeRun: install
